[package]
name = "tokio-udev"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]
license = "Apache-2.0/MIT"
description = "Tokio support for udev device events."
repository = "https://github.com/jeandudey/tokio-udev"
homepage = "https://github.com/jeandudey/tokio-udev"
documentation = "https://docs.rs/tokio-udev"

[dependencies]
libc = "0.2"

mio = "0.6"
mio-udev = { path = "../mio-udev", version = "0.1" }

futures = "0.1"
tokio-reactor = "0.1"

[dev-dependencies]
tokio = "0.1"
